name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
      - "v*.*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: iOS
          os: macos-latest
          target: iOS

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # This is correct. It builds each platform separately.
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package Builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      # THIS IS THE CRUCIAL STEP WE WERE MISSING.
      # This action automatically downloads all the separate build artifacts
      # and combines their .geode files into one directory.
      - name: Combine Builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: package

      # This is the uploader. It takes the output from the "Combine Builds" step
      # and uploads it to the release page.
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          # This correctly points to the output directory from the 'package' step
          files: ${{ steps.package.outputs.build-output }}/*.geode
          fail_on_unmatched_files: true