name: Build Geode Mod

on:
  # This keeps the manual run button
  workflow_dispatch:

  # This is the section we are fixing
  push:
    branches:
      - "master"  # It's better practice to specify 'master' or 'main' instead of '**'
    tags:
      - "v*.*.*"  # This runs the action on tags like v1.0.6
      - "v*.*"    # This runs the action on tags like v1.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: iOS
          os: macos-latest
          target: iOS

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package Builds
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          # THIS IS THE FIX:
          name: Geode Build Results
          path: ./dist
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.geode
          fail_on_unmatched_files: true
